apiVersion: apps/v1
kind: Deployment
metadata:
  name: mssql-deployment
  namespace: contoso-sports
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mssql
  template:
    metadata:
      labels:
        app: mssql
    spec:
      containers:
      - name: mssql
        image: mcr.microsoft.com/mssql/server:2022-latest
        ports:
        - containerPort: {{ .Values.mssql.port }}
        env:
        - name: ACCEPT_EULA
          value: "{{ .Values.mssql.acceptEula }}"
        - name: MSSQL_SA_PASSWORD
          value: "{{ .Values.mssql.saPassword }}"
---
apiVersion: v1
kind: Service
metadata:
  name: mssql-service
  namespace: contoso-sports
spec:
  selector:
    app: mssql
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433